# inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/initializers/devise.rb'
    - 'public/**/*'
  DisplayCopNames: true
  StyleGuideCopsOnly: true

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/BarePercentLiterals:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'lib/**/version.rb'

Style/CommentAnnotation:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/StringLiterals:
  Enabled: false
